In [3]:
from sklearn.feature_selection import SelectKBest, chi2
import pandas as pd

In [4]:
Location = r'c:\C:\Users\Panu\GoogleDrive\01_DataScience\Datasets'

df = pd.read_csv('Diabetes.csv')

In [5]:
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [7]:
array = df.values

In [8]:
array

array([[6, 148, 72, ..., 0.627, 50, 'YES'],
       [1, 85, 66, ..., 0.35100000000000003, 31, 'NO'],
       [8, 183, 64, ..., 0.672, 32, 'YES'],
       ...,
       [5, 121, 72, ..., 0.245, 30, 'NO'],
       [1, 126, 60, ..., 0.349, 47, 'YES'],
       [1, 93, 70, ..., 0.315, 23, 'NO']], dtype=object)

In [9]:
X = array[:,0:8]
#Train set

In [11]:
y = array[:,8]
#this is dependent

In [12]:
test_size = 0.33

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = test_size)

In [16]:
print(df.shape)

(768, 9)


In [17]:
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [18]:
test = SelectKBest(score_func= chi2,k=4)
# k= 4 mean select top 4 features

In [19]:
fit = test.fit(X,y)

In [20]:
import numpy as np

In [21]:
np.set_printoptions(precision=3)

In [23]:
print(fit.scores_)

# give the features for each of the score

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [24]:
print('***************** Higher the score better the features predict ***********************')
    

***************** Higher the score better the features predict ***********************


In [27]:
features = fit.transform(X)

In [29]:
print(features[0:5,:])
#print 5 rows all features which is only 4 coln or 4 features

[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]


In [30]:
print('***************** Lets try the features on the mondel ***********************')


***************** Lets try the features on the mondel ***********************


In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
from sklearn.model_selection import train_test_split

In [36]:
model = LogisticRegression()

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y)
#this is using all features and we have not done the feature selction here

In [37]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [38]:
model.score(X_train,y_train)
#this give the accuracy

0.7743055555555556

In [39]:
# SO LESTS RETURN with Feature selection with only selected features

In [41]:
X_train,X_test,y_train,y_test = train_test_split(features,y)

# Here we are using features instead of X

In [42]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [44]:
model.score(X_train,y_train)


# It may worsening here sometimes

0.765625

In [45]:



# recursive feature elimination, feature selection technique

# gvs the combination of features which gv btr accuracy



#from sklearn.linear_model import LogisticRegression

#from sklearn.model_selection import train_test_split logreg = LogisticRegression()




In [46]:
## RFE Recursive Feature elimination

In [47]:
from sklearn.feature_selection import RFE

In [54]:
rfe = RFE(model,3)

# we will use 3 features only best combination of 3 features

import sklearn



In [55]:
fit = rfe.fit(X,y) 

In [59]:
print("Number of features: %d " % fit.n_features_) 


# gvs num of features


Number of features: 3 


In [61]:
print("Selected features: %s " % fit.support_) 


# gvs bool vals, which features hv been selected by feature selection mod


Selected features: [ True False False False False  True  True False] 


In [65]:
print("Feature Ranking: %s " % fit.ranking_)
print("Features sorted by their rank:")

Feature Ranking: [1 2 3 5 6 1 1 4] 
Features sorted by their rank:


In [67]:
print(sorted(zip(map(lambda x: round(x, 4), rfe.ranking_))))


[(1,), (1,), (1,), (2,), (3,), (4,), (5,), (6,)]


In [68]:
### PCA ### Dim Reduction Techniq

# unlike SelectKBest it is not just eliminating the features

# but it is creating new features called as components

# so it is referred as a dim reduction techniq



In [71]:
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [72]:
from sklearn.decomposition import PCA

In [73]:
pca = PCA(n_components=None)

In [75]:
fit = pca.fit(X)

In [76]:
print("Explanin Variance Ratio %s:",fit.explained_variance_ratio_)

Explanin Variance Ratio %s: [8.885e-01 6.159e-02 2.579e-02 1.309e-02 7.441e-03 3.026e-03 5.124e-04
 6.793e-06]


In [77]:
#[  8.885e-01   6.159e-02   2.579e-02   1.309e-02   7.441e-03   3.026e-03

#   5.124e-04   6.793e-06]

# First PC explains 88%

# First 2 PCs explain 88 + 6 = 94% and so on...
'''''

In [78]:
print(fit.components_)

[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02
   5.372e-04 -3.565e-03]
 [-2.265e-02 -9.722e-01 -1.419e-01  5.786e-02  9.463e-02 -4.697e-02
  -8.168e-04 -1.402e-01]
 [-2.246e-02  1.434e-01 -9.225e-01 -3.070e-01  2.098e-02 -1.324e-01
  -6.400e-04 -1.255e-01]
 [-4.905e-02  1.198e-01 -2.627e-01  8.844e-01 -6.555e-02  1.928e-01
   2.699e-03 -3.010e-01]
 [ 1.516e-01 -8.794e-02 -2.322e-01  2.600e-01 -1.723e-04  2.147e-02
   1.641e-03  9.205e-01]
 [-5.047e-03  5.074e-02  7.564e-02  2.214e-01 -6.133e-03 -9.708e-01
  -2.029e-03 -1.511e-02]
 [ 9.867e-01  8.834e-04 -1.230e-03 -3.764e-04  1.423e-03 -2.730e-03
  -6.344e-03 -1.626e-01]
 [ 6.101e-03 -8.255e-04  5.209e-04 -2.549e-03 -2.690e-04 -2.673e-03
   1.000e+00 -1.953e-03]]


In [79]:
pca = PCA(n_components=3)

In [80]:
fit = pca.fit(X)

In [81]:
print("Explain Variance Ratio %s:",fit.explained_variance_ratio_)

Explain Variance Ratio %s: [0.889 0.062 0.026]


In [88]:
# Explained Variance Ratio %s: [ 0.889  0.062  0.026] '''
#First set of components capture 88.9% of the variance and the second set of components 6%


#This is the first component

#[ -2.022e-03   9.781e-02   1.609e-02   6.076e-02   9.931e-01   1.401e-02 5.372e-04  -3.565e-03]
#and so on... '''




In [94]:



# Extra Tree Classifier

from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()

model.fit(X,y)

# The higher the vals the btr the features are

# drop the low val features







ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [97]:
print(model.feature_importances_)

# the higher the value but the features are


# drop the low values


[0.11  0.226 0.097 0.087 0.069 0.148 0.128 0.135]
